### ISSUE TITLE
(Feature Request) allow tracking file in directories other than just home.

### ISSUE THREAD

**Issue by nerd190** [alphabetum/bindle#7]
First, thank you, this is great, I have no idea why it isnt more popular!
GNU Stow allows us to create our own nested directory within dotfiles folder and link them, please add this if possible.
I know it can do one directory deep but from readme it seems (I could be wrong!) that it cant do any deeper, example:
For Bindle that would mean allowing us to create directories in the "home" directory like so:
- home
  - git
    - ExamplePkg
      - ExamplePkgsFile.rc

Only thing to note if you do is you would probably have to change the name of "local" to something like "untracked" as most people have a ".local" directory and (like me) would probably like to track this (I personally have alot more binaries in ~/.local/bin I would like to track than in ~/bin).
Thank you again! its really appreciated!

**Comment by xwmx** [comment]
Thanks! I haven't used Stow for a while and will have to take a look.

Regarding nesting, `bindle` handles links to the top level of `$HOME`, aka `~/`, and subdirectories can be included or excluded using `.gitignore` files. The directories in [the example dotfiles repo](https://github.com/xwmx/dotfiles/tree/master/home) are configured like this. For example, my [`~/.config`](https://github.com/xwmx/dotfiles/tree/master/home/.config) directory is linked from `~/.config` to `~/.bindle/home/.config`, which is where all the files are, and there are a bunch of rules in the [top-level `.gitignore`](https://github.com/xwmx/dotfiles/blob/master/.gitignore#L64) first ignoring everything in the directory and then explicitly specifying which files to track. This is a bit of a manual process, but `~/.config` has a ton of different subdirectories and the things being tracked are at different nesting levels, and `.gitignore` would be used for specifying the tracked files if just `git` was being used alone. By including the entire directories in `~/.bindle/home`, it also provides the benefit of making the entire directory contents easily accessible when opening the `~/.bindle` directory in an editor, including the untracked / ignored configuration files.

So for `~/.local` I would do the exact same thing as the `~/.config` example, linking the whole directory with `bindle track .local`, then editing `.gitignore` with something like:

```gitignore
# home/.local
#
# Only track specific .local files
#
# Exclude all .local files by default:
/home/.local/*
# Include .local/example/example.config
!/home/.local/example/example.config
````

I hope all that makes sense! I'll take a look at stow and think about this a bit more.

**Comment by nerd190** [comment]
@xwmx Thank you! Actually that now makes TOTAL SENSE!
Like I said before, I genuinely have no idea why more people dont go this solution! It is much more capable and flexible than say "stow", but since discussing this, perhaps it is the simplicity/automation that the average user likes? I will also take a look, two heads are better than one.
Gotta say, being a bash-hacker, I am a big fan of all your projects, they are all very nice shell solutions, thank you!

**Comment by xwmx** [comment]
:blush: Thanks!! Glad you find them useful.

**Comment by nerd190** [comment]
I cant believe I never closed this 6 months ago! my apologies!
P.S I'm still using Bindle! 👍
